version: "3.9"

services:
  app:
    build:
      context: .
      target: "${LBT_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    image: "${LBTIMAGE_NAME:-lbt}:${LBT_IMAGE_TAG:-development}"
    env_file:
      - .env
    environment:
      PYLINTHOME: /app/.pylint.d
    volumes:
      - .:/app

  locust-master:
    image: locustio/locust:2.9.0
    ports:
     - "8089:8089"
    volumes:
      - ./src:/mnt/locust
    depends_on:
      - locust-worker
    command: -f /mnt/locust/locustfile.py --master -H ${TARGET_HOST}
                                          --lrs-login ${LRS_LOGIN}
                                          --lrs-password ${LRS_PASSWORD}
                                          # --headless -u ${USER_NUMBER} -r ${SPAWN_RATE}
                                          # --expect-workers ${SLAVES_NUMBER}
  locust-worker:
    image: locustio/locust:2.9.0
    volumes:
      - ./src:/mnt/locust
      - ./data:/mnt/data
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master

  datasim:
    image: yetanalytics/datasim:0.1.7
    env_file:
      - env.d/datasim
    volumes:
      - ./data:/data

  # -- Tools --
  dockerize:
    image: jwilder/dockerize

  netshoot:
    image: nicolaka/netshoot
