version: "3.9"

services:

  locust-master:
    image: locustio/locust:2.9.0
    ports:
     - "8089:8089"
    volumes:
      - ./src:/mnt/locust
      - ./results:/mnt/results
    depends_on:
      - locust-worker
    command: -f /mnt/locust/locustfile.py --master -H "http://${LRS}:${LRS_PORT}/${ENDPOINT_PREFIX}"
                                          --lrs-login ${LRS_LOGIN}
                                          --lrs-password ${LRS_PASSWORD}
                                          --csv=/mnt/results/${LRS}
                                          --expect-workers ${WORKERS_NUMBER}
                                          --run-time ${RUN_TIME}
                                          --stop-timeout ${STOP_TIMEOUT}
                                          --headless -u ${USERS_NUMBER} -r ${SPAWN_RATE}
  locust-worker:
    image: locustio/locust:2.9.0
    volumes:
      - ./src:/mnt/locust
      - ./data:/mnt/data
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master

  datasim:
    image: yetanalytics/datasim:0.1.7
    env_file:
      - env.d/datasim
    volumes:
      - ./data:/data

  # -- Tools --
  dockerize:
    image: jwilder/dockerize

  notebook:
    image: jupyter/base-notebook
    user: ${DOCKER_USER:-1000}
    environment:
      NB_UID: ${DOCKER_UID:-1000}
      NB_GID: ${DOCKER_GID:-1000}
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
      - ./data:/mnt/data
