version: "3.9"

services:

  locust:
    image: locustio/locust:2.9.0
    ports:
     - "8089:8089"
    working_dir: /app
    volumes:
      - ./src:/app/locust
      - ./data:/app/data
      - ./runs:/app/runs

  datasim:
    image: yetanalytics/datasim:latest
    environment:
      - CREDENTIALS=admin:funfunfun
      - API_ALLOWED_ORIGINS=*
    volumes:
      - ./data:/data

  notebooks-notebook:
    build: ./notebooks
    user: ${DOCKER_USER:-1000}
    environment:
      NB_UID: ${DOCKER_UID:-1000}
      NB_GID: ${DOCKER_GID:-1000}
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
      - ./results:/mnt/results


  # -- Tools --
  dockerize:
    image: jwilder/dockerize
