version: "3.9"

services:

  locust-master:
    build: .
    ports:
     - "8089:8089"
    volumes:
      - ./src:/mnt/locust
      - ./data:/mnt/data
      - ./results:/mnt/results
    depends_on:
      - locust-worker
    command: -f /mnt/locust/${SCENARIO}.py
             -H "http://${LRS}:${LRS_PORT}/${ENDPOINT_PREFIX}"
             --lrs-login ${LRS_LOGIN}
             --lrs-password ${LRS_PASSWORD}
             --csv=/mnt/results/${LRS}_${SCENARIO}_${ITERATION}
             --run-time ${RUN_TIME}s
             --stop-timeout ${STOP_TIMEOUT}
             --headless -u ${USERS_NUMBER} -r ${SPAWN_RATE}
             --master
             --expect-workers=${WORKERS_NUMBER}

  locust-worker:
    build: .
    volumes:
      - ./src:/mnt/locust
      - ./data:/mnt/data
    command: -f /mnt/locust/${SCENARIO}.py 
             --worker 
             --master-host locust-master
  datasim:
    image: yetanalytics/datasim:latest
    environment:
      - CREDENTIALS=admin:funfunfun
      - API_ALLOWED_ORIGINS=*
    volumes:
      - ./data:/data

  notebooks-notebook:
    build: ./notebooks
    user: ${DOCKER_USER:-1000}
    environment:
      NB_UID: ${DOCKER_UID:-1000}
      NB_GID: ${DOCKER_GID:-1000}
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
      - ./results:/mnt/results


  # -- Tools --
  dockerize:
    image: jwilder/dockerize
