version: "3.9"

services:

  lrsql:
    image: yetanalytics/lrsql:latest
    command:
      - /lrsql/bin/run_postgres.sh
    ports:
      - "8090:8090"
    depends_on:
      - lrsql-postgres
    env_file:
      - ./stores/lrsql/env.d/.env

  lrsql-postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./stores/lrsql/env.d/.env