version: "3.9"

services:

  ralph-proxy:
    image: caddy:2.5.1
    restart: unless-stopped
    ports:
      - "8090:8090"
    command: caddy reverse-proxy --from :8090 --to ralph-server:8091
    depends_on:
      - ralph-server

  ralph-server:
    image: fundocker/ralph:latest
    command:
      - ralph
      - "-v"
      - DEBUG
      - runserver
      - "-b"
      - "${RALPH_RUNSERVER_BACKEND:-es}"
    env_file:
      - ./stores/ralph/env.d/env
    ports:
      - "8091:8091"
    depends_on:
      - ralph-es

  ralph-es:
    image: elasticsearch:8.1.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    mem_limit: 2g
