version: "3.9"

services:

  ralph:
    image: fundocker/ralph:latest
    env_file:
      - ./stores/ralph/env.d/env
    ports:
      - "${RALPH_RUNSERVER_PORT:-8090}:${RALPH_RUNSERVER_PORT:-8090}"
    command:
      - "uvicorn"
      - "ralph.api:app"
      - "--proxy-headers"
      - "--workers"
      - "1"
      - "--host"
      - "${RALPH_RUNSERVER_HOST:-0.0.0.0}"
      - "--port"
      - "${RALPH_RUNSERVER_PORT:-8090}"
    volumes:
      - ./stores/ralph/:/app
    depends_on:
      - ralph-es

  ralph-es:
    image: elasticsearch:8.1.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
    mem_limit: 2g
